import '~/styles/globals.css'
import { Inter } from 'next/font/google'
import { TRPCReactProvider } from '~/trpc/react'
import { type ReactNode } from 'react'
import { Header } from '~/components/layout/header'
import { Content } from '~/components/layout/content'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <TRPCReactProvider>
          <div className="holy-grail mx-auto grid min-h-screen max-w-[70rem] grid-cols-1 grid-rows-[auto_1fr_auto] gap-y-4">
            <Header />
            <main className="mt-6 grid grid-cols-1 grid-rows-1 gap-10 px-4">
              <Content>{children}</Content>
            </main>
            <footer className="footer grid justify-center py-8 text-muted-foreground">
              MindsBytes@2024
            </footer>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
